// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4nte-AeHAT0xPs5a9YJ7WJS8-DiugWlA',
    appId: '1:190941704849:web:47f75e734ffbbd1c124530',
    messagingSenderId: '190941704849',
    projectId: 'messagingapp-feb93',
    authDomain: 'messagingapp-feb93.firebaseapp.com',
    databaseURL: 'https://messagingapp-feb93-default-rtdb.firebaseio.com',
    storageBucket: 'messagingapp-feb93.firebasestorage.app',
    measurementId: 'G-SCLP2RCTNM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5-T3HIX6tEyRVu8vUVdf2ODYyZ9nYkUM',
    appId: '1:190941704849:android:3c8440037a94852b124530',
    messagingSenderId: '190941704849',
    projectId: 'messagingapp-feb93',
    databaseURL: 'https://messagingapp-feb93-default-rtdb.firebaseio.com',
    storageBucket: 'messagingapp-feb93.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzgru9e0SVkPxgZ-Fy53gH_7v8dyqRLK0',
    appId: '1:190941704849:ios:b782e9e79a1bb3e5124530',
    messagingSenderId: '190941704849',
    projectId: 'messagingapp-feb93',
    databaseURL: 'https://messagingapp-feb93-default-rtdb.firebaseio.com',
    storageBucket: 'messagingapp-feb93.firebasestorage.app',
    iosBundleId: 'com.example.flutterRiverpodExamples',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGzmHZYR4S6S6ArFx1Xu9vi3gYNt82N5A',
    appId: '1:190941704849:web:d4970939452bcba7124530',
    messagingSenderId: '190941704849',
    projectId: 'messagingapp-feb93',
    authDomain: 'messagingapp-feb93.firebaseapp.com',
    databaseURL: 'https://messagingapp-feb93-default-rtdb.firebaseio.com',
    storageBucket: 'messagingapp-feb93.firebasestorage.app',
    measurementId: 'G-9MSPS0607C',
  );
}
